name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, arm, amd64, 386]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
          - name: darwin
            os: macos-latest
        exclude:
          - os: macos-latest
            arch: 386
          - os: macos-latest
            arch: arm
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=${{ matrix.name }} GOARCH=${{ matrix.arch }} go build -o dist/go-encrypt-sending-${{ matrix.name }}-${{ matrix.arch }} main.go

